from __future__ import annotations

from typing import Any


VERDICT_THRESHOLDS = {
    "robust": "stability score >= 0.75",
    "suspicious": "0.50 <= stability score < 0.75",
    "fragile": "stability score < 0.50",
}


def build_kiro_verdict_explanation(audit_result: dict[str, Any]) -> dict[str, Any]:
    verdict = str(audit_result.get("verdict", "unknown"))
    stability_score = float(audit_result.get("stability_score", 0.0))
    per_type_scores = audit_result.get("per_type_scores", {}) or {}
    warnings = audit_result.get("warnings", []) or []
    biomarkers = audit_result.get("biomarkers", []) or []
    weakest_name, weakest_score = weakest_perturbation(per_type_scores)
    artifact_count = sum(1 for item in biomarkers if item.get("one_run_artifact"))

    evidence = [
        {
            "label": "Verdict source",
            "value": "computed stability metrics",
            "interpretation": "Kiro explains the completed audit result but does not choose or override the verdict.",
        },
        {
            "label": "Stability score",
            "value": f"{stability_score:.3f}",
            "interpretation": threshold_interpretation(verdict, stability_score),
        },
    ]
    if weakest_name:
        evidence.append(
            {
                "label": "Weakest perturbation",
                "value": f"{weakest_name.replace('_', ' ')} ({weakest_score:.3f})",
                "interpretation": "This stress test contributed the weakest support for the claim.",
            }
        )
    evidence.append(
        {
            "label": "Biomarker stability",
            "value": f"{artifact_count} one-run artifact(s)",
            "interpretation": biomarker_interpretation(artifact_count, len(biomarkers)),
        }
    )

    return {
        "mode": "kiro_guided_explanation",
        "verdict_source": "computed_metrics",
        "kiro_role": "orchestrate, explain, and enforce guardrails",
        "headline": headline(verdict, stability_score),
        "summary": summary(verdict, stability_score, weakest_name, weakest_score, artifact_count),
        "threshold_used": VERDICT_THRESHOLDS.get(verdict, "unknown threshold"),
        "evidence": evidence,
        "reasoning_steps": [
            "Read the completed audit artifact generated by the analysis engine.",
            "Use the same stability thresholds from the deterministic verdict logic.",
            "Identify the weakest perturbation score and biomarker artifact warnings.",
            "Translate the computed evidence into cautious research-support language.",
        ],
        "guardrails": [
            "The verdict is computed by deterministic code, not generated by an LLM.",
            "Kiro can explain only metrics and artifacts present in the audit result.",
            "The explanation must not claim clinical validation, diagnosis, or treatment guidance.",
        ],
        "warnings": warnings,
        "next_steps": next_steps(verdict, weakest_name, artifact_count),
    }


def weakest_perturbation(per_type_scores: dict[str, float]) -> tuple[str, float]:
    if not per_type_scores:
        return "", 0.0
    name = min(per_type_scores, key=per_type_scores.get)
    return name, float(per_type_scores[name])


def threshold_interpretation(verdict: str, stability_score: float) -> str:
    if verdict == "robust":
        return f"The score clears the robust threshold of 0.75 by {stability_score - 0.75:.3f}."
    if verdict == "suspicious":
        return "The score is above the fragile range but below the robust threshold."
    if verdict == "fragile":
        return f"The score is {0.50 - stability_score:.3f} below the suspicious threshold."
    return "No recognized verdict threshold was found."


def biomarker_interpretation(artifact_count: int, biomarker_count: int) -> str:
    if not biomarker_count:
        return "No ranked biomarkers were returned for this audit."
    if artifact_count:
        return "Some top markers were not consistently recovered across perturbation runs."
    return "Top ranked markers were not flagged as one-run artifacts in the returned audit."


def headline(verdict: str, stability_score: float) -> str:
    if verdict == "robust":
        return f"Kiro explanation: the claim is robust at {stability_score:.3f} stability."
    if verdict == "suspicious":
        return f"Kiro explanation: the claim needs review at {stability_score:.3f} stability."
    if verdict == "fragile":
        return f"Kiro explanation: the claim is fragile at {stability_score:.3f} stability."
    return "Kiro explanation: verdict unavailable."


def summary(
    verdict: str,
    stability_score: float,
    weakest_name: str,
    weakest_score: float,
    artifact_count: int,
) -> str:
    weak_text = (
        f"The weakest stress test was {weakest_name.replace('_', ' ')} at {weakest_score:.3f}. "
        if weakest_name
        else ""
    )
    artifact_text = (
        f"{artifact_count} top biomarker(s) behaved like one-run artifacts. "
        if artifact_count
        else "The returned top biomarkers were not flagged as one-run artifacts. "
    )
    return (
        f"Kiro is summarizing the audit evidence for a {verdict} verdict from a "
        f"{stability_score:.3f} stability score. {weak_text}{artifact_text}"
        "This is an explanation of computed evidence, not an independent biological conclusion."
    )


def next_steps(verdict: str, weakest_name: str, artifact_count: int) -> list[str]:
    steps = [
        "Review the exported reproducibility report and dataset hash before sharing results.",
        "Validate promising biomarkers in an independent cohort before making a research claim.",
    ]
    if weakest_name:
        steps.insert(0, f"Inspect the {weakest_name.replace('_', ' ')} perturbation because it was the weakest test.")
    if verdict != "robust":
        steps.insert(0, "Treat the current claim as a hypothesis that needs more evidence.")
    if artifact_count:
        steps.append("Down-rank markers flagged as one-run artifacts until they replicate across perturbations.")
    return steps
